
#ifndef __DEBICT_ROBOTTA_CONTROLLER__ROBOTTA_CONTROLLER_COMPILER_H__
#define __DEBICT_ROBOTTA_CONTROLLER__ROBOTTA_CONTROLLER_COMPILER_H__

#if defined _WIN32 || defined __CYGWIN__
#   ifdef __GNUC__
#       define DEBICT_ROBOTTA_CONTROLLER_EXPORT __attribute__((dllexport))
#       define DEBICT_ROBOTTA_CONTROLLER_IMPORT __attribute__((dllimport))
#   else
#       define DEBICT_ROBOTTA_CONTROLLER_EXPORT __declspec(dllexport)
#       define DEBICT_ROBOTTA_CONTROLLER_IMPORT __declspec(dllimport)
#   endif
#   ifdef DEBICT_ROBOTTA_CONTROLLER_BUILDING_DLL
#       define DEBICT_ROBOTTA_CONTROLLER_PUBLIC DEBICT_ROBOTTA_CONTROLLER_EXPORT
#   else
#       define DEBICT_ROBOTTA_CONTROLLER_PUBLIC DEBICT_ROBOTTA_CONTROLLER_IMPORT
#   endif
#   define DEBICT_ROBOTTA_CONTROLLER_PUBLIC_TYPE DEBICT_ROBOTTA_CONTROLLER_PUBLIC
#   define DEBICT_ROBOTTA_CONTROLLER_LOCAL
#else
#   define DEBICT_ROBOTTA_CONTROLLER_EXPORT __attribute__((visibility("default")))
#   define DEBICT_ROBOTTA_CONTROLLER_IMPORT
#   if __GNUC__ >= 4
#       define DEBICT_ROBOTTA_CONTROLLER_PUBLIC __attribute__((visibility("default")))
#       define DEBICT_ROBOTTA_CONTROLLER_LOCAL __attribute__((visibility("hidden")))
#   else
#       define DEBICT_ROBOTTA_CONTROLLER_PUBLIC
#       define DEBICT_ROBOTTA_CONTROLLER_LOCAL
#   endif
#   define DEBICT_ROBOTTA_CONTROLLER_PUBLIC_TYPE
#endif

#endif // __DEBICT_ROBOTTA_CONTROLLER__ROBOTTA_CONTROLLER_COMPILER_H__