<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.5"/>
    <xacro:property name="chassis_width" value="0.5"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="3.5"/>    <!-- nilai asal-->
    <xacro:property name="chassis_upper_length" value = "0.05"/>
    <xacro:property name="chassis_upper_width" value = "0.30"/>
    <xacro:property name="chassis_upper_height" value = "0.515"/>
    <xacro:property name="chassis_upper_mass" value = "0.01"/>
    <xacro:property name="chassis_offset_z" value = "${chassis_upper_height/2 + chassis_height/2}"/>
    <xacro:property name="wheel_radius" value="0.0825"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="wheel_mass" value="2.0"/>    <!-- nilai asal-->
    <xacro:property name="wheel_offset_x" value="0.1"/>
    <xacro:property name="wheel_offset_y" value="0.25"/>    <!-- nilai asal-->
    <xacro:property name="wheel_offset_z" value="0.05"/>
    <xacro:property name="caster_wheel_radius" value="0.03"/>
    <xacro:property name="caster_wheel_mass" value="1.5"/>     <!-- nilai asal-->
    <xacro:property name="caster_wheel_offset_x" value="0.45"/>
    <xacro:property name="caster_wheel_offset_y" value="0.20"/>  <!-- nilai asal-->
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>


    <!-- BASE LINK -->

    <link name="base_link">   
    
    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="${wheel_offset_x} 0 ${-wheel_offset_z}" />   <!-- titik cartesian untuk robot-->
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz = "${-chassis_length/2} 0 ${chassis_height/2}" />  <!-- titik cartesian untuk rangka badan-->
            <geometry>
                <box size= "${chassis_length} ${chassis_width} ${chassis_height}" />   <!-- geometry dari rangka badan xyz = 30x30x15 cm-->
            </geometry>
            <material name ="white"/>
        </visual>
        <collision>
            <origin xyz = "${chassis_length/2} 0 ${chassis_height/2}" />  <!-- titik cartesian untuk rangka badan-->
            <geometry>
                <box size= "${chassis_length} ${chassis_width} ${chassis_height}" />   <!-- geometry dari rangka badan xyz = 30x30x15 cm-->
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- CHASSIS UPPER LINK -->

    <joint name="chassis_upper_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis_upper" />
        <origin xyz="0 0 ${chassis_offset_z}" />   <!--titik cartesian untuk robot-->
    </joint>

    <link name="chassis_upper">
        <visual>
            <!-- <origin xyz = "0 0 0.15" />  titik cartesian untuk rangka badan -->
            <geometry>
                <box size= "${chassis_upper_length} ${chassis_upper_width} ${chassis_upper_height}" />   <!--geometry dari rangka badan xyz = 15x15x30 cm -->
            </geometry>
            <material name ="white"/>
        </visual>
        <collision>
            <!-- <origin xyz = "-0.15 0 -0.075" />  titik cartesian untuk rangka badan -->
            <geometry>
                <box size= "${chassis_upper_length} ${chassis_upper_width} ${chassis_upper_height}" />   <!--geometry dari rangka badan xyz = 15x15x30 cm-->
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_upper_mass}" x="${chassis_upper_length}" y="${chassis_upper_width}" z="${chassis_upper_height}">
            <!-- <origin xyz="-0 0 -0.075" rpy="0 0 0"/> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_upper">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="${-pi/2} 0 0"/>
        <!-- <origin xyz="0 ${-wheel_offset_y} 0" rpy="${-pi/2} 0 0"/> -->
        <axis xyz = "0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>   <!-- geometry dari roda kiri-->
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>   <!-- collision dari roda kiri-->
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
        <!-- <origin xyz="0 ${wheel_offset_y} 0" rpy="${pi/2} 0 0"/> -->
        <axis xyz = "0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>   <!-- geometry dari roda kiri-->
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.0815" length="0.05"/>   <!-- collision dari roda kiri-->
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL LEFT LINK -->

    <joint name="left_caster_wheel_joint" type="fixed">
        <parent link="chassis" />   
        <child link="left_caster_wheel" />
        <origin xyz="${-caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}" rpy="${-pi/2} 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <link name="left_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="left_caster_wheel">
        <material>Gazebo/Orange</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- CASTER WHEEL RIGHT LINK -->

    <joint name="right_caster_wheel_joint" type="fixed">
        <parent link="chassis" />   
        <child link="right_caster_wheel" />
        <origin xyz="${-caster_wheel_offset_x} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}" rpy="${pi/2} 0 0"/>
        <axis xyz = "0 0 -1"/>
    </joint>

    <link name="right_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="right_caster_wheel">
        <material>Gazebo/Orange</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>